#
#Wed May 27 21:47:10 COT 2026
acceptInsecureCerts=false
browserName=chrome
goog\:chromeOptions={args\=[--incognito, --disable-notifications, --disable-gpu, --no-sandbox, --disable-dev-shm-usage, --window-size\=1920,1080, --headless\=new, remote-allow-origins\=*], extensions\=[], prefs\={credentials_enable_service\=false, autofill.credit_card_enabled\=false, autofill.profile_enabled\=false, profile.password_manager_enabled\=false}}
